### PR TITLE
Improving website

### PR DESCRIPTION
**Pull request by satanas**
This PR solves https://github.com/nodeschool/seattle/issues/46, adding a new style (matching the Seahawks colors), a code of conduct and updating the content.

This is how the new site looks like:
website-preview

You can compare it with [San Francisco's](https://nodeschool.io/sanfrancisco/) and [Oakland's](https://nodeschool.io/oakland/) chapters.

### CODE REVIEW

**Comment by satanas** [comment]
@sethvincent here is the PR that fixes #46. Feel free to update your twitter handler (and Justin's) after merge.

**Comment by strugee** [comment]
Based on the branch name I'm assuming "We <3 NodeSchool SF!" is because the design is stole^W^W borrowed from them? That's not clear in the website, though, and the shoutout seems a bit arbitrary :)

**Comment by satanas** [comment]
@strugee Turns out that @Xabadu (from SF chapter) is a very good friend of mine and he's not only readily lending us the website code, the wiki and all the content they already have for SF (borrowed too but from the Oakland folks) but also is willing to help us with the restart of the Seattle chapter. So, I thought it would be a good idea to spread the love among communities that are helping each other 😉

**Comment by strugee** [comment]
@satanas definitely like the idea :thumbsup:

I still think it should be clearer in the website though, e.g.:

> Thanks to NodeSchool SF for lending us their resources! <3

**Comment by satanas** [comment]
@strugee Fair point. I'll update the message to make it clearer 👍

**Comment by satanas** [comment]
@Xabadu thanks for the feedback! I'm gonna add a new icon and update the PR

**Comment by JustinBeckwith** [comment]
This looks rad.  Thank you!

**Comment by satanas** [comment]
Comments addressed and screenshot updated. Still need the URLs for mentors and mentees, and @CADBOT's twitter handler to complete all the data.

**Comment by satanas** [comment]
Ok folks, I just added the links. Everything is set and we're ready to roll 😈

**Comment by JustinBeckwith** [comment]
Merged!  Anyone know how these changes roll out to https://nodeschool.io/seattle/?

**Comment by strugee** [comment]
@JustinBeckwith looks like it's already live? Citation Needed™ but IIRC nodeschool.io is just GitHub Pages + Cloudflare

**Comment by strugee** [comment]
Hah, nevermind. Just saw the discussion in #46 :P

**Pull request merged**
