### PR TITLE
Adding script to generate social image

### PR DESCRIPTION
**Pull request by satanas**
This PR fixes https://github.com/nodeschool/seattle/issues/54

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
LGTM!

**Comment by satanas** [comment]
@Xabadu could you please take a look and merge if everything is ok? Thanks!

**Comment by Xabadu** [comment]
Hey @satanas, looks good to me. One question though, should this PR be against master?

**Comment by satanas** [comment]
@Xabadu that's a good question. I don't remember 😜. What base branch do you use for the PRs in SF?

**Comment by Xabadu** [comment]
`master`

**Comment by satanas** [comment]
@Xabadu done! Now `master` is the base branch

**Pull request merged**
